/**
 * Shared frontend type definitions.
 *
 * These types mirror the Rust-side structs in `src-tauri/src/spotify.rs`,
 * `src-tauri/src/teams.rs`, `src-tauri/src/commands.rs`, and
 * `src-tauri/src/config.rs`. They live here (not in `src/lib/stores/`)
 * because they're pure data shapes, not reactive state.
 *
 * **`SpotifyTokens`, `TrackInfo`, `TeamsTokens`, `DeviceCodeResponse`,
 * `SyncStatus`, `AppConfig` are generated by ts-rs from the Rust
 * definitions at `cargo test` time.** The `types-generated/` files are
 * the source of truth — re-exported here so the existing
 * `import type { SpotifyTokens } from '$lib/types'` consumers
 * continue to work. Do NOT hand-edit these types; change the Rust
 * struct, run `cargo test`, and the regenerated `.ts` will flow
 * through this re-export. See issue #78.
 *
 * **`ErrorEventPayload` and `LogPayload` are still hand-written**
 * because their wire shape is not owned by a Rust struct (the polling
 * loop emits `ErrorEventPayload` via `serde_json::json!({...})` inline
 * — see `polling.rs::emit_error`; `LogPayload` comes from the
 * `tauri-plugin-log` plugin, not from this crate's structs). See
 * issue #79 for the inline-emit rationale.
 */
export type { SpotifyTokens } from './types-generated/SpotifyTokens';
export type { TrackInfo } from './types-generated/TrackInfo';
export type { TeamsTokens } from './types-generated/TeamsTokens';
export type { DeviceCodeResponse } from './types-generated/DeviceCodeResponse';
export type { SyncStatus } from './types-generated/SyncStatus';
export type {
  AppConfig,
} from './types-generated/AppConfig';
export type { DiagnosticsSnapshot } from './types-generated/DiagnosticsSnapshot';
/**
 * Payload of the `error` event emitted by the Rust polling loop. The
 * `severity` field was added in #79 part 1; the Dashboard.svelte
 * listener uses it to gate the red banner (only `severity: "error"`
 * pops it; `severity: "warning"` is logged to the console for the
 * developer but does not alarm-fatigue the user).
 */
export interface ErrorEventPayload {
  source: string;
  message: string;
  severity: 'warning' | 'error';
}

/**
 * Payload of the `log://log` event emitted by `tauri-plugin-log`. The
 * plugin's actual payload shape includes a `target` string and several
 * timestamp fields; we narrow defensively in the listener to the
 * fields the app actually uses. The full plugin type lives in
 * `@tauri-apps/plugin-log` if a strict import is preferred later.
 */
export interface LogPayload {
  level: number;
  message: string;
}