/**
 * Shared frontend type definitions.
 *
 * These types mirror the Rust-side structs in `src-tauri/src/spotify.rs`,
 * `src-tauri/src/teams.rs`, `src-tauri/src/commands/`, and
 * `src-tauri/src/config.rs`. They live here (not in `src/lib/stores/`)
 * because they're pure data shapes, not reactive state.
 *
 * **`SpotifyTokens`, `TrackInfo`, `TeamsTokens`, `DeviceCodeResponse`,
 * `SyncStatus`, `AppConfig` are generated by ts-rs from the Rust
 * definitions at `cargo test` time.** The `types-generated/` files are
 * the source of truth — re-exported here so the existing
 * `import type { SpotifyTokens } from '$lib/types'` consumers
 * continue to work. Do NOT hand-edit these types; change the Rust
 * struct, run `cargo test`, and the regenerated `.ts` will flow
 * through this re-export. See issue #78.
 *
 * **`ErrorEventPayload` and `LogPayload` are hand-written** because the
 * `tauri-plugin-log` payload is not owned by this crate, while the error
 * payload mirrors the canonical Rust `ErrorEventPayload` in
 * `polling/mod.rs`. Keep the two definitions synchronized when the wire shape
 * changes. See issue #79 for the event rationale.
 */
export type { SpotifyTokens } from './types-generated/SpotifyTokens';
export type { TrackInfo } from './types-generated/TrackInfo';
export type { TeamsTokens } from './types-generated/TeamsTokens';
export type { DeviceCodeResponse } from './types-generated/DeviceCodeResponse';
export type { SyncStatus } from './types-generated/SyncStatus';
export type {
  AppConfig,
} from './types-generated/AppConfig';
export type { DiagnosticsSnapshot } from './types-generated/DiagnosticsSnapshot';
/**
 * Issue #968: typed reason codes for Settings-card errors. Generated from
 * `src-tauri/src/commands/shortcut_reason.rs::ShortcutReason` at
 * `cargo test` time; do not hand-edit. Re-exported here so the Settings
 * card can `import type { ShortcutReason } from '$lib/types'`.
 */
export type { ShortcutReason } from './types-generated/ShortcutReason';
export type { SlotRegistration } from './types-generated/SlotRegistration';
/**
 * Issue #782: the updater banner's payloads are generated from
 * `src-tauri/src/updater_bg.rs` (`#[ts(export)]`) instead of being mirrored by
 * hand in `UpdatePrompt.svelte`. A Rust-side rename now fails
 * `npm run check` rather than leaving the banner reading `undefined` at
 * runtime. `UpdateCheckOutcome.install` (issue #894) tells the banner whether
 * this install is in-app-updatable or owned by a system package manager.
 */
export type { StageDeferredOutcome } from './types-generated/StageDeferredOutcome';
export type { StageProgress } from './types-generated/StageProgress';
export type { StageProgressEvent } from './types-generated/StageProgressEvent';
export type { StageComplete } from './types-generated/StageComplete';
export type { UpdateCheckOutcome } from './types-generated/UpdateCheckOutcome';
// `UpdateInstall` is its own ts-rs module (issue #894), not a member of
// `UpdateCheckOutcome` — re-exporting it from there fails type-check.
export type { UpdateInstall } from './types-generated/UpdateInstall';
export type { CancelDeferredOutcome } from './types-generated/CancelDeferredOutcome';
export type { CancelDeferredState } from './types-generated/CancelDeferredState';
export type { ShortcutsStatus } from './types-generated/ShortcutsStatus';
/**
 * Payload of the `error` event emitted by the Rust polling loop. The
 * `severity` field was added in #79 part 1. Dashboard.svelte uses it to
 * gate the red fatal banner: only `severity: "error"` is shown there,
 * while a Teams `severity: "warning"` with `recovery: "retry_scheduled"`
 * is rendered as a non-fatal `role="status"` warning banner. Other warnings
 * are ignored by the user-facing Dashboard listener.
 */
export interface ErrorEventPayload {
  source: string;
  message: string;
  severity: 'warning' | 'error';
  recovery?: 'retry_scheduled' | 'reconnect_required' | 'user_action_required';
}

/**
 * Payload of the `log://log` event emitted by `tauri-plugin-log`. The
 * plugin's actual payload shape includes a `target` string and several
 * timestamp fields; we narrow defensively in the listener to the
 * fields the app actually uses. The full plugin type lives in
 * `@tauri-apps/plugin-log` if a strict import is preferred later.
 */
export interface LogPayload {
  level: number;
  message: string;
}