import { writable } from 'svelte/store';
import { invoke } from '@tauri-apps/api/core';
import type { AppConfig } from '../types';

/**
 * Frontend mirror of the Rust `AppConfig` defaults.
 *
 * Typed with an assertion rather than a bare literal because
 * `src/lib/types-generated/` is derived (gitignored, regenerated by
 * `cargo test`): a 4.6 field added on the Rust side must be mirrored here in
 * the same PR, and the assertion keeps both the pre- and post-regeneration
 * shapes type-checking instead of making the frontend gate depend on
 * whether the bindings happened to be regenerated yet. Field/value mistakes
 * on the keys both shapes share are still caught.
 */
export const defaultConfig: AppConfig = {
  spotify: {
    client_id: '',
    client_secret_set: false,
    // 4.6 (issue #560): Rust's `ClientSecretState`, stamped on every config
    // load from the OS keychain. Read it through `clientSecretStateOf`, never
    // by field, so a binding that has not been regenerated yet cannot break
    // type-check. See that helper for why `absent` is the safe default.
    client_secret_state: 'absent',
    redirect_uri: 'presencejam://callback'
  },
  teams: {
    status_format: '🎵 {artist} - {track} 🎧',
    clear_on_pause: true,
    profanity_filter: true,
    // Canonical frontend default for the profanity placeholder (issue
    // #342). Onboarding and Settings import it from here instead of
    // hardcoding their own copies. The Rust backend's canonical default
    // (profanity::safe_placeholder_default, via config.rs) carries the
    // same text at runtime and owns the whitespace fallback.
    profanity_placeholder: 'Currently Listening to Spotify',
    start_minimized: false,
    availability_sync: false,
    presence_gate: true,
    // 4.6 (issue #538): user lexicon for the profanity filter, bounded to
    // 64 entries of 32 chars by Rust's `clamp_teams`.
    profanity_extra_words: [],
    // 4.6 (finding #635): a status message the user set by hand is never
    // overwritten. ON by default, mirroring Rust's serde default.
    respect_manual_status: true,
    // 4.6 (finding #637): the out-of-office gate is opt-in, like
    // `availability_sync` before it.
    gate_when_out_of_office: false,
    // 4.7.0 — S4 (issue #672): the user-templatable paused/stopped status
    // texts. Rust keeps the emoji prefix out of the field, so these mirror
    // the serde defaults verbatim.
    paused_status_format: 'Paused',
    stopped_status_format: 'Nothing playing on Spotify'
  },
  polling: {
    default_interval_seconds: BigInt(30),
    minimum_interval_seconds: BigInt(10),
    max_interval_seconds: BigInt(60),
    expiry_buffer_seconds: BigInt(10),
    // 4.6 (issue #538): ceiling for the paused-playback backoff, clamped to
    // 60..=3600 by Rust's `clamp_polling`.
    pause_backoff_max_seconds: BigInt(300)
  },
  logging: {
    enabled: true,
    log_level: 'Info',
    // 4.7.0: log rotation. `max_file_size_mb` is a Rust `u64`, so ts-rs types
    // it `bigint` — see `BIGINT_SECTIONS` below; `keep_files` is a `u32`
    // (`number`). Both mirror `config.rs`'s serde defaults and its
    // `clamp_logging` band (1..=500 MB, 1..=20 files).
    max_file_size_mb: BigInt(10),
    keep_files: 3
  },
  autostart: false,
  // 4.7.0 (#675): one desktop-notification class per toggle, all ON — the
  // Rust `NotificationsConfig` defaults (serde-defaulted, so a pre-4.7
  // config loads unchanged). The pre-4.7 single opt-in is migrated into
  // `track_change` by `stores/notifications.ts`.
  notifications: {
    track_change: true,
    sync_stopped: true,
    auth_required: true,
    update_staged: true
  },
  // 4.7.0 (issue #674): `AppConfig::locale` — the single source of truth for
  // the UI language (webview, tray and native application menu). `null` reads
  // as English on both sides, the documented default of a pre-4.7 config.
  locale: null,
  // Issue #432: mirrors Rust StatusRulesConfig::default (empty rule lists).
  status_rules: { quiet_hours: [], track_rules: [] },
  // Mirrors Rust `config::SCHEMA_VERSION` (issues #379 / #536). The backend
  // stamps the persisted value itself, so this is only the pre-load
  // placeholder — it is never trusted as an instruction.
  schema_version: 2
} as AppConfig;

/**
 * The frontend mirror of Rust's `config::ClientSecretState` (issue #560):
 * the three answers the OS keychain can give about the stored Spotify
 * `client_secret`.
 */
export type ClientSecretState = 'present' | 'absent' | 'unavailable';

/**
 * Read the derived keychain tri-state out of a config.
 *
 * Deliberately not a direct field read: `src/lib/types-generated/` is a
 * symlink shared by every worktree and is regenerated by `cargo test`, so the
 * generated `SpotifyConfig` a given checkout type-checks against may not
 * carry the field yet. Anything that is not the `present`/`unavailable` wire
 * spelling falls back to `client_secret_set` — the pre-4.6 answer, which at
 * worst reports a locked keychain as merely absent, never the reverse.
 *
 * `absent` is the only state a UI may act on by sending the user to setup. A
 * locked or missing keychain (`unavailable`) must never be rendered as "not
 * configured": the secret is still stored, merely unreadable right now.
 */
export function clientSecretStateOf(cfg: AppConfig): ClientSecretState {
  // `in`-narrowing, not a cast: the generated `SpotifyConfig` describes the
  // field once the bindings carry it, and this stays honest when they do not.
  const spotify: unknown = cfg.spotify;
  if (spotify !== null && typeof spotify === 'object' && 'client_secret_state' in spotify) {
    const raw: unknown = spotify.client_secret_state;
    if (raw === 'present' || raw === 'unavailable' || raw === 'absent') return raw;
  }
  return cfg.spotify.client_secret_set ? 'present' : 'absent';
}

/**
 * Single frontend canonical source for the profanity placeholder default
 * (issue #342). Import this instead of hardcoding the string; Settings'
 * reset-to-default reads the same value through `defaultConfig`.
 *
 * The setup wizard no longer imports it: since #531/#542 it merges into the
 * STORED config, so it never seeds a placeholder of its own.
 */
export const DEFAULT_PROFANITY_PLACEHOLDER = defaultConfig.teams.profanity_placeholder;

export const configStore = writable<AppConfig>(structuredClone(defaultConfig));

/**
 * Whether {@link configStore} currently holds a document that came from the
 * backend rather than the frontend defaults.
 *
 * `false` until the first `load_config` / `save_config` / `update_config`
 * round-trip resolves, so a consumer that must not act on the defaults can
 * wait for the real document. The i18n store's one-shot legacy-locale
 * migration is the first such consumer (4.7.0, issue #674): acting on the
 * boot-time default emission would write a stale `localStorage` value over a
 * locale that is persisted on disk.
 *
 * A failed `load_config` leaves it `false` — the store then holds defaults,
 * not truth, and nothing may be written back on their behalf.
 */
export const configHydrated = writable(false);

/**
 * Rust `u64` fields are ts-rs `bigint` on the wire, and every one of them
 * needs the same rounding/normalisation on the way in and out; a hand-edited
 * `config.json` that carries a section but omits or nulls one of its fields
 * used to leave the store holding `undefined`, which `toSavePayload` turned
 * into `NaN` → `null` and Rust's serde rejected (issue #541).
 *
 * Keyed by section, with the `defaultConfig` mirror of that section as the
 * fallback: the ts-rs bindings in `src/lib/types-generated/` are derived
 * (gitignored, regenerated by `cargo test`), so a field added on the Rust
 * side cannot be read here by name until they have been regenerated — but its
 * default must still be reachable by the key-driven normalisation either way.
 * `logging.max_file_size_mb` is the second such field (4.7.0).
 */
const POLLING_KEYS = [
  'default_interval_seconds',
  'minimum_interval_seconds',
  'max_interval_seconds',
  'expiry_buffer_seconds',
  'pause_backoff_max_seconds'
] as const;

/**
 * `defaultConfig.<section>` viewed as a plain map. The ts-rs bindings in
 * `src/lib/types-generated/` are derived (gitignored, regenerated by
 * `cargo test`), so a field added on the Rust side cannot be read here by
 * name until they have been regenerated — but its default must still be
 * reachable by the key-driven normalisation below either way.
 */
const DEFAULT_POLLING = defaultConfig.polling as unknown as Record<string, unknown>;
const DEFAULT_LOGGING = defaultConfig.logging as unknown as Record<string, unknown>;

const BIGINT_SECTIONS = [
  { section: 'polling', keys: POLLING_KEYS, defaults: DEFAULT_POLLING },
  {
    section: 'logging',
    keys: ['max_file_size_mb'] as const,
    defaults: DEFAULT_LOGGING
  }
] as const;

let loadPromise: Promise<AppConfig> | null = null;
let savePromise: Promise<AppConfig> | null = null;

function normalizeLoadedConfig(cfg: AppConfig): AppConfig {
  const c = cfg as unknown as Record<string, Record<string, unknown> | undefined>;
  for (const group of BIGINT_SECTIONS) {
    const section = c[group.section];
    if (!section) continue;
    for (const key of group.keys) {
      const value = section[key];
      if (typeof value === 'bigint') continue;
      const numeric =
        typeof value === 'number' || typeof value === 'string' ? Number(value) : NaN;
      // Issue #541: a missing, null or unparsable field falls back to the
      // default instead of leaving `undefined` in the store — mirroring the
      // status_rules deep-backfill below.
      section[key] = Number.isFinite(numeric)
        ? BigInt(Math.trunc(numeric))
        : group.defaults[key];
    }
  }
  // Issue #432: pre-4.5 backends omit `status_rules` (Rust serde default
  // covers the backend side); deep-backfill here so the Settings rules
  // card never binds against undefined — including hand-edited configs
  // that carry the section but lack one of the arrays.
  const r = cfg as unknown as {
    status_rules?: { quiet_hours?: unknown[]; track_rules?: unknown[] } | null;
  };
  if (r.status_rules == null) {
    r.status_rules = { quiet_hours: [], track_rules: [] };
  } else {
    if (!Array.isArray(r.status_rules.quiet_hours)) r.status_rules.quiet_hours = [];
    if (!Array.isArray(r.status_rules.track_rules)) r.status_rules.track_rules = [];
  }
  return cfg;
}

export function toSavePayload(cfg: AppConfig): AppConfig {
  const payload = structuredClone(cfg) as unknown as Record<
    string,
    Record<string, unknown> | undefined
  >;
  for (const group of BIGINT_SECTIONS) {
    const section = payload[group.section];
    if (!section) continue;
    for (const key of group.keys) {
      const numeric = Number(section[key] as bigint | number | string);
      // Issues #297/#541: the payload is JSON, so a `bigint` would throw and
      // a `NaN` would serialize as `null` and be rejected by Rust's `u64`.
      // Neither may ever reach `invoke('save_config')`.
      section[key] = Number.isFinite(numeric)
        ? Math.trunc(numeric)
        : Number(group.defaults[key]);
    }
  }
  return payload as unknown as AppConfig;
}

/**
 * The fields the setup wizard owns (issues #531/#542). Everything else in a
 * stored config is out of its reach.
 */
export interface WizardConfigFields {
  spotify_client_id: string;
  status_format: string;
  default_interval_seconds: bigint;
  autostart: boolean;
}

/**
 * Merge the wizard's fields INTO a stored config instead of replacing it
 * (issues #531 / #542).
 *
 * The wizard is reachable by returning users (Dashboard's `goToSetup`,
 * Settings' "Run onboarding", Reconnect), so a replace would silently reset
 * their quiet hours, track rules, profanity filter, polling bounds, logging
 * level and `start_minimized` to the wizard's hardcoded defaults. Only the
 * four wizard-owned fields are written here; `status_rules`, `logging`,
 * `clear_on_pause`, `profanity_filter`, `profanity_placeholder`,
 * `presence_gate`, `availability_sync`, `extra` and `schema_version` are
 * carried over verbatim.
 *
 * Pure, so the merge guarantee is unit-testable without mounting the
 * component or touching the Tauri bridge.
 */
export function mergeWizardConfig(
  stored: AppConfig,
  fields: WizardConfigFields
): AppConfig {
  const cfg = structuredClone(stored);
  cfg.spotify.client_id = fields.spotify_client_id;
  // The secret went to the OS keychain during the OAuth flow; both derived
  // keychain fields are kept truthful for the immediate post-save store
  // update (#560). They must move together: `clientSecretStateOf` prioritises
  // the state, so writing only the bool would leave the pair disagreeing and
  // Settings' credential row reading "Not configured" until the next
  // `load_config`.
  cfg.spotify.client_secret_set = true;
  cfg.spotify.client_secret_state = 'present';
  cfg.teams.status_format = fields.status_format;
  // The wizard's "Launch at login" toggle drives both the OS autostart
  // entry and the tray-only start behaviour, as it did before this change.
  cfg.teams.start_minimized = fields.autostart;
  cfg.polling.default_interval_seconds = fields.default_interval_seconds;
  cfg.autostart = fields.autostart;
  return cfg;
}

export async function loadConfig(): Promise<AppConfig> {
  if (loadPromise) return loadPromise;

  loadPromise = (async () => {
    try {
      const cfg = await invoke<AppConfig>('load_config');
      const normalized = normalizeLoadedConfig(cfg);
      configStore.set(normalized);
      configHydrated.set(true);
      return normalized;
    } catch (e) {
      console.error('[CONFIG] loadConfig failed:', e);
      const fallback = structuredClone(defaultConfig);
      configStore.set(fallback);
      return fallback;
    } finally {
      loadPromise = null;
    }
  })();

  return loadPromise;
}

export async function saveConfig(cfg: AppConfig): Promise<AppConfig> {
  if (savePromise) await savePromise;

  savePromise = (async () => {
    try {
      const payload = toSavePayload(cfg);
      // Issue #297: the backend persists a CLAMPED copy and returns it, so
      // adopt that value for the store. Storing `cfg` here left the UI
      // showing a value (e.g. a typed 999) that was never written to disk.
      const persisted = await invoke<AppConfig>('save_config', { config: payload });
      const normalized = normalizeLoadedConfig(persisted);
      configStore.set(normalized);
      configHydrated.set(true);
      return normalized;
    } finally {
      savePromise = null;
    }
  })();

  return savePromise;
}

/**
 * Field-level write for callers that hold only part of the config
 * (CfgDiag#0 / issue #535). The backend merges the patch into the stored
 * document, so a caller can name one field and be certain the rest of the
 * user's settings survive.
 *
 * Prefer this over [`saveConfig`] whenever the caller's `AppConfig` was not
 * read from the store in the same breath.
 */
export interface ConfigPatchPayload {
  spotify?: Partial<AppConfig['spotify']>;
  teams?: Partial<AppConfig['teams']>;
  polling?: Partial<AppConfig['polling']>;
  logging?: Partial<AppConfig['logging']>;
  autostart?: boolean;
  status_rules?: Partial<AppConfig['status_rules']>;
}

export async function updateConfig(patch: ConfigPatchPayload): Promise<AppConfig> {
  if (savePromise) await savePromise;

  savePromise = (async () => {
    try {
      const payload = structuredClone(patch) as unknown as {
        polling?: Record<string, unknown>;
      };
      const p = payload.polling;
      if (p) {
        for (const key of POLLING_KEYS) {
          if (!(key in p)) continue;
          const numeric = Number(p[key] as bigint | number | string);
          p[key] = Number.isFinite(numeric)
            ? Math.trunc(numeric)
            : Number(DEFAULT_POLLING[key]);
        }
      }
      const persisted = await invoke<AppConfig>('update_config', { patch: payload });
      const normalized = normalizeLoadedConfig(persisted);
      configStore.set(normalized);
      configHydrated.set(true);
      return normalized;
    } finally {
      savePromise = null;
    }
  })();

  return savePromise;
}
