//! Machine-readable reason codes for Settings error messages (issue #968).
//!
//! `tauri-plugin-global-shortcut` and `tauri-plugin-autostart` surface failure
//! details as Rust strings, which the Settings card used to splice verbatim
//! into localized copy (a German card shows e.g. `Nicht verwendbar: "Ctrl+P"
//! is not a recognised shortcut (NotAKey)`). Each variant is the user-facing
//! reason key the frontend maps to a dictionary entry; the unknown variant
//! carries through any text the plugin emitted, for genuinely foreign codes
//! (compositor refusals, a partial IPC payload, a future regression).
//!
//! Wire form is a serde-tagged enum so the frontend can switch on `kind`:
//! `{"kind": "NotAKey", "accelerator": "..."}`. The `ts(export)` annotation
//! keeps `SlotRegistration.error` and friends in lock-step with the generated
//! `SlotRegistration.ts` — same denylist-only, autogenerated source of truth
//! as the other Settings-card structs.

use serde::Serialize;

impl std::fmt::Display for ShortcutReason {
    /// Rust-side log representation: the variant name and the data the
    /// frontend would render, so a `log::warn!("… {reason}")` looks the
    /// same as the localized card minus the dictionary entry (the Settings
    /// UI is the source of truth for what the user sees; this is for the
    /// developer reading the log).
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ShortcutReason::NotAKey { accelerator } => {
                write!(f, "NotAKey(\"{accelerator}\")")
            }
            ShortcutReason::Conflict { other_slot } => {
                write!(f, "Conflict(\"{other_slot}\")")
            }
            ShortcutReason::NeedsModifier { accelerator } => {
                write!(f, "NeedsModifier(\"{accelerator}\")")
            }
            ShortcutReason::Autostart { cause } => {
                write!(f, "Autostart(\"{cause}\")")
            }
            ShortcutReason::Unknown { message } => {
                write!(f, "Unknown(\"{message}\")")
            }
        }
    }
}

/// A typed reason code for a Settings-card error.
///
/// `Unknown` is the escape hatch: it carries the backend's free-form text so
/// a refusal the plugin can describe (`accelerator already in use`) reaches
/// the user without the IPC contract needing a new variant every time the
/// plugin changes its error vocabulary. Tests and the frontend agree on
/// `Unknown` meaning "untranslated, fall back to the message".
#[derive(Debug, Clone, PartialEq, Eq, Serialize, ts_rs::TS)]
#[serde(tag = "kind", rename_all = "PascalCase")]
#[ts(export, export_to = "../../src/lib/types-generated/")]
pub enum ShortcutReason {
    /// The stored accelerator did not parse (`validate_accelerator`'s
    /// `.parse::<Shortcut>()` failed). Carries the offending string so the
    /// card can name it; the parse error itself is omitted (it is the
    /// plugin's word choice, not ours).
    NotAKey { accelerator: String },
    /// Two slots resolved to the same parsed accelerator. `other_slot` is
    /// the slot wire name (`toggle_playback` / `toggle_sync`) the other row
    /// already holds — the frontend substitutes it into the localized
    /// `settings.shortcutReasonConflict` template.
    Conflict { other_slot: String },
    /// A modifier-less binding that would grab a bare key system-wide
    /// (issue #810). Carries the offending accelerator so the card can name
    /// it; function keys (F1–F24) and media keys are exempt and never reach
    /// this variant.
    NeedsModifier { accelerator: String },
    /// `set_autostart_enabled` failed: the OS auto-launch manager refused
    /// the toggle. `cause` is the plugin's error text, captured rather than
    /// emitted verbatim so the Settings copy is renderable in every locale.
    Autostart { cause: String },
    /// A genuinely foreign reason — a plugin refusal we cannot translate
    /// (the Wayland case: the compositor owns the combo and the plugin
    /// answers with whatever it answers with). The `message` is what the
    /// backend said, and the card renders it through the unknown template.
    Unknown { message: String },
}

impl ShortcutReason {
    /// An unparseable plugin accelerator: the row's stored value did not
    /// match any accepted spelling. The original parse error is dropped
    /// (`NotAKey` covers it).
    pub fn not_a_key(accelerator: &str) -> Self {
        ShortcutReason::NotAKey {
            accelerator: accelerator.trim().to_string(),
        }
    }

    /// Two slots resolved to one accelerator.
    pub fn conflict(other_slot: &str) -> Self {
        ShortcutReason::Conflict {
            other_slot: other_slot.to_string(),
        }
    }

    /// A modifier-less binding that would swallow a bare key in every
    /// application (issue #810): `Escape` needs at least one modifier.
    pub fn needs_modifier(accelerator: &str) -> Self {
        ShortcutReason::NeedsModifier {
            accelerator: accelerator.trim().to_string(),
        }
    }

    /// An autostart toggle refusal: capture the plugin's text, classify it
    /// so the Settings card can localize it.
    pub fn autostart(cause: &str) -> Self {
        ShortcutReason::Autostart {
            cause: cause.to_string(),
        }
    }

    /// A foreign reason: render verbatim through the unknown template.
    pub fn unknown(message: &str) -> Self {
        ShortcutReason::Unknown {
            message: message.to_string(),
        }
    }
}
#[cfg(test)]
mod tests {
    use super::*;

    /// Serde's tagged-enum format — the wire shape the frontend's switch on
    /// `kind` depends on. A drift (externally tagged, `kind` lowercase, &c.)
    /// silently breaks the Settings card with no compile error.
    #[test]
    fn tagged_enum_wire_shape() {
        let reason = ShortcutReason::not_a_key("NotAKey+Alt");
        let json = serde_json::to_value(&reason).expect("serializable");
        assert_eq!(
            json,
            serde_json::json!({"kind": "NotAKey", "accelerator": "NotAKey+Alt"})
        );

        let conflict = ShortcutReason::conflict("toggle_sync");
        let json = serde_json::to_value(&conflict).expect("serializable");
        assert_eq!(
            json,
            serde_json::json!({"kind": "Conflict", "other_slot": "toggle_sync"})
        );

        // Issue #810: the modifier-less rejection is a typed variant, so the
        // Settings card maps it to `settings.shortcutReasonNeedsModifier`
        // instead of dumping the backend's English text.
        let bare = ShortcutReason::needs_modifier("Escape");
        let json = serde_json::to_value(&bare).expect("serializable");
        assert_eq!(
            json,
            serde_json::json!({"kind": "NeedsModifier", "accelerator": "Escape"})
        );

        let autostart = ShortcutReason::autostart("permission denied");
        let json = serde_json::to_value(&autostart).expect("serializable");
        assert_eq!(
            json,
            serde_json::json!({"kind": "Autostart", "cause": "permission denied"})
        );

        let unknown = ShortcutReason::unknown("some plugin error");
        let json = serde_json::to_value(&unknown).expect("serializable");
        assert_eq!(
            json,
            serde_json::json!({"kind": "Unknown", "message": "some plugin error"})
        );
    }

    /// The frontend's switch cases are PascalCase ("NotAKey", not
    /// "not_a_key"). A rename here without a frontend change silences
    /// every card to the `Unknown` fallback.
    #[test]
    fn variant_names_are_pascal_case() {
        for (variant, expected) in [
            (ShortcutReason::not_a_key("x"), "NotAKey"),
            (ShortcutReason::conflict("y"), "Conflict"),
            (ShortcutReason::needs_modifier("z"), "NeedsModifier"),
            (ShortcutReason::autostart("z"), "Autostart"),
            (ShortcutReason::unknown("w"), "Unknown"),
        ] {
            let json = serde_json::to_value(variant).expect("serializable");
            assert_eq!(json["kind"], expected, "kind drifted for {expected}");
        }
    }
}
