/**
 * #531 / #542 — the setup wizard must MERGE into the stored config, never
 * replace it.
 *
 * The wizard is reachable by returning users from three live entry points
 * (Dashboard `goToSetup`, Settings' "Run onboarding", Reconnect), and the
 * pre-4.6 `finish()` built a whole `AppConfig` from the component's own
 * defaults — silently resetting the user's quiet hours, track rules,
 * profanity filter/placeholder, polling bounds, logging level and
 * `start_minimized`. These tests pin the merge guarantee at the level the
 * wizard actually uses: `mergeWizardConfig` is the single place `finish()`
 * derives the payload it hands to `saveConfig`.
 *
 * Fail pre-fix (with a replace-style literal these values are gone), pass
 * post-fix.
 */
import { describe, it, expect } from 'vitest';
import { mergeWizardConfig, defaultConfig } from '$lib/stores/config';
import type { AppConfig } from '$lib/types';

/**
 * A stored config that differs from `defaultConfig` in every field the
 * wizard used to hardcode. The `as AppConfig` assertion keeps this fixture
 * working whether or not `src/lib/types-generated/` (derived, regenerated by
 * `cargo test`) has picked up the 4.6 additions yet.
 */
function storedConfig(): AppConfig {
  return {
    spotify: {
      client_id: 'stored-client-id',
      client_secret_set: true,
      redirect_uri: 'presencejam://callback'
    },
    teams: {
      status_format: 'Stored {artist}',
      clear_on_pause: false,
      profanity_filter: false,
      profanity_placeholder: 'Custom placeholder',
      start_minimized: true,
      availability_sync: true,
      presence_gate: false
    },
    polling: {
      default_interval_seconds: BigInt(45),
      minimum_interval_seconds: BigInt(20),
      max_interval_seconds: BigInt(120),
      expiry_buffer_seconds: BigInt(5)
    },
    logging: { enabled: false, log_level: 'Debug' },
    autostart: false,
    status_rules: {
      quiet_hours: [
        {
          enabled: true,
          start_minutes: 1320,
          end_minutes: 420,
          days: [1, 2, 3, 4, 5],
          replacement_status: 'Busy'
        }
      ],
      track_rules: [
        {
          enabled: true,
          artist_substring: 'lofi',
          track_substring: '',
          replacement_status: 'Focus'
        }
      ]
    },
    schema_version: 2
  } as unknown as AppConfig;
}

const wizardFields = {
  spotify_client_id: 'new-client-id',
  status_format: 'New {artist}',
  default_interval_seconds: BigInt(15),
  autostart: true
};

describe('mergeWizardConfig (#531, #542)', () => {
  it('writes the fields the wizard owns', () => {
    const merged = mergeWizardConfig(storedConfig(), wizardFields);

    expect(merged.spotify.client_id).toBe('new-client-id');
    expect(merged.spotify.client_secret_set).toBe(true);
    expect(merged.teams.status_format).toBe('New {artist}');
    expect(merged.polling.default_interval_seconds).toBe(BigInt(15));
    expect(merged.autostart).toBe(true);
  });

  it('carries over every field the wizard does not own', () => {
    const merged = mergeWizardConfig(storedConfig(), wizardFields);

    // The #531 losses: user rules authored in Settings.
    expect(merged.status_rules.quiet_hours).toHaveLength(1);
    expect(merged.status_rules.quiet_hours[0]).toEqual({
      enabled: true,
      start_minutes: 1320,
      end_minutes: 420,
      days: [1, 2, 3, 4, 5],
      replacement_status: 'Busy'
    });
    expect(merged.status_rules.track_rules).toHaveLength(1);
    expect(merged.status_rules.track_rules[0].replacement_status).toBe('Focus');

    // Filter and presence preferences.
    expect(merged.teams.profanity_filter).toBe(false);
    expect(merged.teams.profanity_placeholder).toBe('Custom placeholder');
    expect(merged.teams.clear_on_pause).toBe(false);
    expect(merged.teams.availability_sync).toBe(true);
    expect(merged.teams.presence_gate).toBe(false);

    // Polling bounds the wizard used to pin to 10/60, and the logging level.
    expect(merged.polling.minimum_interval_seconds).toBe(BigInt(20));
    expect(merged.polling.max_interval_seconds).toBe(BigInt(120));
    expect(merged.polling.expiry_buffer_seconds).toBe(BigInt(5));
    expect(merged.logging).toEqual({ enabled: false, log_level: 'Debug' });

    // The backend owns the schema version; the wizard must not reset it.
    expect(merged.schema_version).toBe(2);
  });

  it('does not mutate the stored config it was given', () => {
    const stored = storedConfig();
    const before = JSON.stringify(stored, (_k, v) => (typeof v === 'bigint' ? String(v) : v));

    mergeWizardConfig(stored, wizardFields);

    expect(
      JSON.stringify(stored, (_k, v) => (typeof v === 'bigint' ? String(v) : v))
    ).toBe(before);
    expect(stored.spotify.client_id).toBe('stored-client-id');
    expect(stored.teams.status_format).toBe('Stored {artist}');
  });

  it('leaves a first-run config at the defaults for everything it does not own', () => {
    const merged = mergeWizardConfig(structuredClone(defaultConfig), wizardFields);

    expect(merged.teams.profanity_filter).toBe(defaultConfig.teams.profanity_filter);
    expect(merged.teams.profanity_placeholder).toBe(
      defaultConfig.teams.profanity_placeholder
    );
    expect(merged.status_rules).toEqual(defaultConfig.status_rules);
    expect(merged.logging).toEqual(defaultConfig.logging);
    expect(merged.polling.minimum_interval_seconds).toBe(
      defaultConfig.polling.minimum_interval_seconds
    );
    expect(merged.polling.max_interval_seconds).toBe(
      defaultConfig.polling.max_interval_seconds
    );
  });
});
