/**
 * The setup wizard is a thin orchestration layer: it forwards each
 * authentication command with the payload the backend expects, delegates
 * Teams polling and expiry rules to the shared auth-flow store, and persists
 * only the four fields it owns by merging them into the stored config.
 *
 * Pure merge behavior is covered below. The mounted cases pin the actual
 * component boundary: command payloads, authentication phase transitions,
 * and finish ordering. Expiry and polling semantics stay in `authFlow.test.ts`
 * so this file does not duplicate the shared implementation's rules.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, cleanup, fireEvent } from '@testing-library/svelte';
import { get } from 'svelte/store';
import { mergeWizardConfig, defaultConfig } from '$lib/stores/config';
import { t } from '$lib/i18n';
import type { AppConfig } from '$lib/types';

// The mount tests below drive the real component, so the Tauri IPC has to be
// mocked before the component and its stores load. `vi.hoisted` (not a plain
// module-level const) because `vi.mock` is hoisted above these imports.
const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));

vi.mock('@tauri-apps/api/core', () => ({ invoke }));
vi.mock('@tauri-apps/api/event', () => ({
  // Mirror the real signature: listen(eventName, handler) → unlisten.
  listen: vi.fn(async () => () => {})
}));

import Onboarding from '$lib/components/Onboarding.svelte';
import { currentView } from '$lib/stores/app';
import { authFlow, resetAuthFlow, setSpotifyPhase, setTeamsPhase } from '$lib/stores/authFlow.svelte';

/**
 * A stored config that differs from `defaultConfig` in every field the
 * wizard used to hardcode. The `as AppConfig` assertion keeps this fixture
 * working whether or not `src/lib/types-generated/` (derived, regenerated by
 * `cargo test`) has picked up the 4.6 additions yet.
 */
function storedConfig(): AppConfig {
  return {
    spotify: {
      client_id: 'stored-client-id',
      client_secret_set: true,
      redirect_uri: 'presencejam://callback'
    },
    teams: {
      status_format: 'Stored {artist}',
      clear_on_pause: false,
      profanity_filter: false,
      profanity_placeholder: 'Custom placeholder',
      start_minimized: true,
      availability_sync: true,
      presence_gate: false
    },
    polling: {
      default_interval_seconds: BigInt(45),
      minimum_interval_seconds: BigInt(20),
      max_interval_seconds: BigInt(120),
      expiry_buffer_seconds: BigInt(5)
    },
    logging: { enabled: false, log_level: 'Debug' },
    autostart: false,
    status_rules: {
      quiet_hours: [
        {
          enabled: true,
          start_minutes: 1320,
          end_minutes: 420,
          days: [1, 2, 3, 4, 5],
          replacement_status: 'Busy'
        }
      ],
      track_rules: [
        {
          enabled: true,
          artist_substring: 'lofi',
          track_substring: '',
          replacement_status: 'Focus'
        }
      ]
    },
    schema_version: 2
  } as unknown as AppConfig;
}

const wizardFields = {
  spotify_client_id: 'new-client-id',
  status_format: 'New {artist}',
  default_interval_seconds: BigInt(15),
  autostart: true
};

describe('mergeWizardConfig (#531, #542)', () => {
  it('writes the fields the wizard owns', () => {
    const merged = mergeWizardConfig(storedConfig(), wizardFields);

    expect(merged.spotify.client_id).toBe('new-client-id');
    expect(merged.spotify.client_secret_set).toBe(true);
    expect(merged.teams.status_format).toBe('New {artist}');
    expect(merged.polling.default_interval_seconds).toBe(BigInt(15));
    expect(merged.autostart).toBe(true);
  });

  it('carries over every field the wizard does not own', () => {
    const merged = mergeWizardConfig(storedConfig(), wizardFields);

    // The #531 losses: user rules authored in Settings.
    expect(merged.status_rules.quiet_hours).toHaveLength(1);
    expect(merged.status_rules.quiet_hours[0]).toEqual({
      enabled: true,
      start_minutes: 1320,
      end_minutes: 420,
      days: [1, 2, 3, 4, 5],
      replacement_status: 'Busy'
    });
    expect(merged.status_rules.track_rules).toHaveLength(1);
    expect(merged.status_rules.track_rules[0].replacement_status).toBe('Focus');

    // Filter and presence preferences.
    expect(merged.teams.profanity_filter).toBe(false);
    expect(merged.teams.profanity_placeholder).toBe('Custom placeholder');
    expect(merged.teams.clear_on_pause).toBe(false);
    expect(merged.teams.availability_sync).toBe(true);
    expect(merged.teams.presence_gate).toBe(false);

    // Polling bounds the wizard used to pin to 10/60, and the logging level.
    expect(merged.polling.minimum_interval_seconds).toBe(BigInt(20));
    expect(merged.polling.max_interval_seconds).toBe(BigInt(120));
    expect(merged.polling.expiry_buffer_seconds).toBe(BigInt(5));
    expect(merged.logging).toEqual({ enabled: false, log_level: 'Debug' });

    // The backend owns the schema version; the wizard must not reset it.
    expect(merged.schema_version).toBe(2);
  });

  it('does not mutate the stored config it was given', () => {
    const stored = storedConfig();
    const before = JSON.stringify(stored, (_k, v) => (typeof v === 'bigint' ? String(v) : v));

    mergeWizardConfig(stored, wizardFields);

    expect(
      JSON.stringify(stored, (_k, v) => (typeof v === 'bigint' ? String(v) : v))
    ).toBe(before);
    expect(stored.spotify.client_id).toBe('stored-client-id');
    expect(stored.teams.status_format).toBe('Stored {artist}');
  });

  it('leaves a first-run config at the defaults for everything it does not own', () => {
    const merged = mergeWizardConfig(structuredClone(defaultConfig), wizardFields);

    expect(merged.teams.profanity_filter).toBe(defaultConfig.teams.profanity_filter);
    expect(merged.teams.profanity_placeholder).toBe(
      defaultConfig.teams.profanity_placeholder
    );
    expect(merged.status_rules).toEqual(defaultConfig.status_rules);
    expect(merged.logging).toEqual(defaultConfig.logging);
    expect(merged.polling.minimum_interval_seconds).toBe(
      defaultConfig.polling.minimum_interval_seconds
    );
    expect(merged.polling.max_interval_seconds).toBe(
      defaultConfig.polling.max_interval_seconds
    );
  });
});

/**
 * #967 — the wizard's escape hatch. A configured install can be dropped into
 * the wizard from Settings' "Run onboarding" (or the boot probe's fail-open
 * path) and must be able to leave without re-entering credentials it cannot
 * read back: the Spotify client secret lives in the OS keychain. A first-run
 * install has nothing to go back to, so it must stay one-way.
 */
function mockBackend(complete: boolean, config: AppConfig = structuredClone(defaultConfig)) {
  invoke.mockImplementation(async (cmd: string) => {
    switch (cmd) {
      case 'load_config':
        return structuredClone(config);
      case 'is_onboarding_complete':
        return complete;
      default:
        return undefined;
    }
  });
}


/** Settle mocked IPC and Svelte's microtask flush scheduler. */
async function settle(rounds = 24) {
  for (let i = 0; i < rounds; i++) await Promise.resolve();
}
/** Mount the wizard and settle its mocked IPC plus Svelte's flush scheduler. */
async function renderWizard(
  complete: boolean,
  config: AppConfig = structuredClone(defaultConfig)
) {
  mockBackend(complete, config);
  const rendered = render(Onboarding);
  await settle();
  return rendered;
}

describe('wizard escape hatch (#967)', () => {
  beforeEach(() => {
    invoke.mockReset();
    resetAuthFlow();
    currentView.set('onboarding');
  });

  afterEach(() => {
    cleanup();
  });

  it('#967 lets a configured install return to the Dashboard', async () => {
    const { getByRole } = await renderWizard(true);

    // The control exists only because the install is already complete.
    await fireEvent.click(getByRole('button', { name: 'Back to dashboard' }));

    expect(get(currentView)).toBe('dashboard');
  });

  it('#967 keeps first-run setup one-way', async () => {
    const { queryByRole } = await renderWizard(false);

    expect(queryByRole('button', { name: 'Back to dashboard' })).toBeNull();
  });
});

describe('mounted wizard command contracts (#763)', () => {
  const spotifyClientId = 'a'.repeat(32);
  const spotifyClientSecret = 'b'.repeat(32);

  beforeEach(() => {
    invoke.mockReset();
    resetAuthFlow();
    currentView.set('onboarding');
  });

  afterEach(() => {
    cleanup();
    vi.useRealTimers();
  });

  it('starts Spotify auth with the credentials and canonical redirect URI', async () => {
    const { container, getByRole } = await renderWizard(false);
    invoke.mockClear();

    await fireEvent.input(container.querySelector('#client-id') as HTMLInputElement, {
      target: { value: spotifyClientId }
    });
    await fireEvent.input(container.querySelector('#client-secret') as HTMLInputElement, {
      target: { value: spotifyClientSecret }
    });
    await fireEvent.click(getByRole('button', { name: t('onboarding.connectSpotify') }));
    await settle();

    expect(invoke).toHaveBeenCalledWith('start_spotify_auth', {
      clientId: spotifyClientId,
      clientSecret: spotifyClientSecret,
      redirectUri: 'presencejam://callback'
    });
    expect(authFlow.spotify.phase).toBe('waiting');
  });

  it('completes Spotify from a manual callback and enters the connected phase', async () => {
    setSpotifyPhase('waiting');
    const { container, getByRole } = await renderWizard(false);
    invoke.mockClear();

    await fireEvent.input(container.querySelector('#manual-url') as HTMLInputElement, {
      target: {
        value: 'presencejam://callback?code=manual-code&state=oauth-state'
      }
    });
    await fireEvent.click(getByRole('button', { name: t('onboarding.submitCode') }));
    await settle();

    expect(invoke).toHaveBeenCalledWith('complete_spotify_auth_manual', {
      code: 'manual-code',
      oauthState: 'oauth-state'
    });
    expect(authFlow.spotify.phase).toBe('done');
  });

  it('starts Teams device auth, opens its verification URL, and delegates polling', async () => {
    setSpotifyPhase('done');
    const { getByRole } = await renderWizard(false);
    await fireEvent.click(getByRole('button', { name: t('onboarding.continue') }));
    await settle();
    invoke.mockClear();

    invoke.mockImplementation(async (command: string) => {
      switch (command) {
        case 'start_teams_auth_device_code':
          return {
            user_code: 'ABCD-EFGH',
            device_code: 'teams-device-code',
            verification_url: 'https://microsoft.com/devicelogin',
            interval: 7,
            expires_in: 900
          };
        case 'open_external_url':
        case 'poll_teams_auth':
          return undefined;
        default:
          return undefined;
      }
    });

    await fireEvent.click(
      getByRole('button', { name: t('onboarding.startMicrosoftSignIn') })
    );
    await settle();

    expect(invoke.mock.calls.map(([command]) => command)).toEqual([
      'start_teams_auth_device_code',
      'open_external_url',
      'poll_teams_auth'
    ]);
    expect(invoke).toHaveBeenCalledWith('open_external_url', {
      url: 'https://microsoft.com/devicelogin'
    });
    expect(invoke).toHaveBeenCalledWith('poll_teams_auth', {
      deviceCode: 'teams-device-code',
      interval: 7
    });
    expect(authFlow.teams.phase).toBe('done');
  });

  async function renderFinishStep(config: AppConfig) {
    setSpotifyPhase('done');
    setTeamsPhase('done');
    const rendered = await renderWizard(false, config);
    await fireEvent.input(rendered.container.querySelector('#client-id') as HTMLInputElement, {
      target: { value: spotifyClientId }
    });
    await fireEvent.click(rendered.getByRole('button', { name: t('onboarding.continue') }));
    await settle();
    await fireEvent.click(rendered.getByRole('button', { name: t('onboarding.continue') }));
    await settle();
    invoke.mockClear();
    return rendered;
  }

  it('merges and saves wizard fields, conditionally enables autostart, and completes last', async () => {
    const config = storedConfig();
    const { container, getByRole } = await renderFinishStep(config);
    let saved: AppConfig | undefined;
    let completeOnboarding!: () => void;
    const completionPending = new Promise<void>((resolve) => {
      completeOnboarding = resolve;
    });

    invoke.mockImplementation(async (command: string, args?: { config?: AppConfig }) => {
      switch (command) {
        case 'load_config':
          return structuredClone(config);
        case 'save_config':
          saved = structuredClone(args?.config);
          return structuredClone(args?.config);
        case 'set_autostart_enabled':
          return undefined;
        case 'complete_onboarding':
          await completionPending;
          return true;
        default:
          return undefined;
      }
    });

    await fireEvent.input(
      container.querySelector('#status-format-onb') as HTMLInputElement,
      { target: { value: 'Listening to {artist}' } }
    );
    await fireEvent.input(container.querySelector('#poll-interval-onb') as HTMLInputElement, {
      target: { value: '25' }
    });
    await fireEvent.click(
      container.querySelector('#launch-at-login-onb') as HTMLInputElement
    );
    await fireEvent.click(getByRole('button', { name: t('onboarding.finishSetup') }));
    await settle();

    expect(invoke.mock.calls.map(([command]) => command)).toEqual([
      'load_config',
      'save_config',
      'set_autostart_enabled',
      'complete_onboarding'
    ]);
    expect(invoke).toHaveBeenCalledWith('set_autostart_enabled', { enabled: true });
    expect(saved?.spotify.client_id).toBe(spotifyClientId);
    expect(saved?.teams.status_format).toBe('Listening to {artist}');
    expect(saved?.polling.default_interval_seconds).toBe(25);
    expect(saved?.autostart).toBe(true);
    expect(saved?.status_rules).toEqual(config.status_rules);

    // The lifecycle is not complete while its final command is still pending,
    // so the wizard must remain mounted and must not expose a false success.
    expect(get(currentView)).toBe('onboarding');

    completeOnboarding();
    await settle();

    expect(get(currentView)).toBe('dashboard');
  });

  it('skips the autostart command when the launch-at-login choice is off', async () => {
    const config = storedConfig();
    const { getByRole } = await renderFinishStep(config);
    let saved: AppConfig | undefined;

    invoke.mockImplementation(async (command: string, args?: { config?: AppConfig }) => {
      if (command === 'load_config') return structuredClone(config);
      if (command === 'save_config') {
        saved = structuredClone(args?.config);
        return structuredClone(args?.config);
      }
      if (command === 'complete_onboarding') return true;
      return undefined;
    });

    await fireEvent.click(getByRole('button', { name: t('onboarding.finishSetup') }));
    await settle();

    expect(saved?.autostart).toBe(false);
    expect(invoke.mock.calls.some(([command]) => command === 'set_autostart_enabled')).toBe(
      false
    );
    expect(invoke).toHaveBeenCalledWith('complete_onboarding');
    expect(get(currentView)).toBe('dashboard');
  });
});

/**
 * Issue #983 — the wizard's poll-interval slider is `min="10" max="60"`, but
 * it used to seed its label from the stored config unchanged. A hand-edited
 * `config.json` (or an imported 4.7 backup) could leave the label reading
 * e.g. "120s" while the thumb sat pinned at the rail, and `finish()` would
 * silently merge the slider's band back through `mergeWizardConfig`.
 *
 * The prefill must clamp, AND the label and thumb must agree, AND the
 * discrepancy must be visible via the inline clamp-hint affordance.
 */
describe('wizard poll-interval clamp (#983)', () => {
  beforeEach(() => {
    invoke.mockReset();
    resetAuthFlow();
    currentView.set('onboarding');
  });

  afterEach(() => {
    cleanup();
  });

  it('#983 clamps an out-of-band stored value into the slider range', async () => {
    // Stored value 120 is above the slider's max="60" — pre-fix this left
    // the label reading "120s" with the thumb pinned at 60.
    const cfg = structuredClone(defaultConfig) as AppConfig;
    cfg.polling.default_interval_seconds = BigInt(120);

    mockBackend(false, cfg);
    // Both auth phases must report 'done' so the Continue buttons render
    // and the test can navigate from step 1 → step 2 → step 3 (where the
    // poll-interval slider lives).
    setSpotifyPhase('done');
    setTeamsPhase('done');

    const rendered = render(Onboarding);
    // Let onMount's prefill IIFE and the auth-flow reactivity settle.
    for (let i = 0; i < 24; i++) await Promise.resolve();

    // Step 1 → Step 2.
    await fireEvent.click(rendered.getByRole('button', { name: 'Continue →' }));
    for (let i = 0; i < 24; i++) await Promise.resolve();
    // Step 2 → Step 3 (the poll-interval step).
    await fireEvent.click(rendered.getByRole('button', { name: 'Continue →' }));
    for (let i = 0; i < 24; i++) await Promise.resolve();

    const slider = rendered.container.querySelector('#poll-interval-onb') as HTMLInputElement;
    // The thumb must reflect the clamped value, not the stored one.
    expect(slider.value).toBe('60');
    expect(Number(slider.value)).toBeLessThanOrEqual(60);
    expect(Number(slider.value)).toBeGreaterThanOrEqual(10);

    // The label reads "How often to check Spotify: Xs" — it must NOT echo
    // the stored 120.
    const labelText = slider.closest('label')?.textContent ?? '';
    expect(labelText).not.toContain('120s');

    // The clamp-hint affordance must be present so the user sees the
    // discrepancy before `finish()` rewrites it into the slider's band.
    expect(rendered.queryByTestId('poll-interval-clamp-hint')).not.toBeNull();
  });

  it('#983 does not show the clamp hint for an in-band stored value', async () => {
    const cfg = structuredClone(defaultConfig) as AppConfig;
    cfg.polling.default_interval_seconds = BigInt(30);

    mockBackend(false, cfg);
    setSpotifyPhase('done');
    setTeamsPhase('done');

    const rendered = render(Onboarding);
    for (let i = 0; i < 24; i++) await Promise.resolve();
    await fireEvent.click(rendered.getByRole('button', { name: 'Continue →' }));
    for (let i = 0; i < 24; i++) await Promise.resolve();
    await fireEvent.click(rendered.getByRole('button', { name: 'Continue →' }));
    for (let i = 0; i < 24; i++) await Promise.resolve();

    expect(rendered.queryByTestId('poll-interval-clamp-hint')).toBeNull();
  });
});
