// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the running install has to be updated (issue #894).
 *
 * `latest.json` publishes exactly one `linux-x86_64` entry and it points at
 * the AppImage, but the plugin's installer branches on the bundle type the
 * running binary was packaged in: a `.deb` install routes to `install_deb`,
 * which rejects AppImage bytes as `invalid updater binary format`, and a run
 * without the AppImage marker falls through to `install_appimage`, which
 * rewrites the binary in place under `/usr` and fails on permissions. So the
 * Debian/Ubuntu/Mint/popOS install SETUP.md recommends could never update at
 * all. The banner says so instead of downloading a payload that cannot be
 * installed.
 */
export type UpdateInstall = { "kind": "in-app" } | { "kind": "deb", 
/**
 * Direct download URL of the `.deb` asset for this version.
 */
package_url: string, } | { "kind": "rpm", 
/**
 * Direct download URL of the `.rpm` asset for this version.
 */
package_url: string, };
